version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "voicesummary"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i4yxx1ug58sq"
s3_prefix = "voicesummary"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
